### ISSUE TITLE
Add primary actors in scenarios and IDs of information exchanged

### ISSUE THREAD

**Issue by marjolainefarretrialog** [smart-grid-use-cases/smart-grid-use-cases.github.io#93]
Hi, when uploading the first use case of MAESHA, I have some difficulties in adding the primary actor of the scenario in the scenario overview section, as well as the ID of the information echanged in the steps-scenario section. How do we have to fill in the Excel file to make them appear in the platform? Do you have an example of a completed Excel file?

**Comment by m-mirz** [comment]
Hi @marjolainefarretrialog, sorry for the delay. You can find completed use cases [here](https://github.com/smart-grid-use-cases/excel2xml-input/tree/master/excel-use-cases).
